### ISSUE TITLE
PROTOCOL_NAME_TYPE identity should inherit from EquipmentAugment

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/lldp#3]
In the generated and published YANG , we have the identities , 

```
identity PROTOCOL_NAME_TYPE {
   description
   "none";
}

identity PROTOCOL_NAME_TYPE_PROTOCOL_NAME_TYPE_LLDP {
  base PROTOCOL_NAME_TYPE;
  description
  "none";
}
```
Additionally we have a type definition for the “protocol-name-type”(which is generated by the tool) irrespective that there is no usage in the current model 
```
typedef protocol-name-type {
            type identityref {
                base PROTOCOL_NAME_TYPE;
            }
            description    
                "List of Protocol names.";
        }
```

We have 2 problems ,
**Problem#1 :**
              typedef protocol-name-type is unused in the current. 
              To resolve this , this typedef shall be removed.
**Problem#2 :**       
            The identity’s base is not referring the parent in the equipment-augment. This makes the identity to not augment to the parent. 
            To resolve this , 
            the identity “identity PROTOCOL_NAME_TYPE” should be removed and the base of the “identity PROTOCOL_NAME_TYPE_PROTOCOL_NAME_TYPE_LLDP” should be “base equipment-augment:PROTOCOL_NAME_TYPE”
            Or 
            the base of the “identity PROTOCOL_NAME_TYPE” should be “base equipment-augment:PROTOCOL_NAME_TYPE”

**Comment by openBackhaul** [comment]
Would agree to Proposal for Problem#1 "We shall enhance the UML2YANG tool to remove any unused typedef."
In regards of how to implement, I would leave the decision to you (maybe Option#2 is a bit more close to the core of the problem, but it's up to you).
Would agree to Proposal for Problem#2 "We shall modify the base of the "identity PROTOCOL_NAME_TYPE” to “base equipment-augment:PROTOCOL_NAME_TYPE” in the post processing.

**Comment by PrathibaJee** [comment]
Closing this issue , as both the mentioned problems are fixed in the LLDP_1.0.0-tsi.230524.1420+yang.1.
Problem#2 : Identity “PROTOCOL_NAME_TYPE_LLDP” augments to the “equipment-augment:PROTOCOL_NAME_TYPE” (Included in the post processing)
Problem#1 : fixed by removing the typedef protocol-name-type based on the “explanatoryOnly” package. Enhanced the tool to not consider a datatype for translation if it is modeled inside a explanatory package.
