### ISSUE TITLE
LLDP protocol enable/disable

### ISSUE THREAD

**Issue by niloda** [openBackhaul/lldp#6]
Some implementation requires an object to globally enable/disable the whole LLDP protocol.
When the LLDP protocol is enabled in the device it can be enabled on port basis. 
When the LLDP protocol is disabled in the device it is also disabled on all ports.

**Comment by openBackhaul** [comment]
**Decision during the LF ONMI x-haul call on 11th of December 2024:**  

The following classes shall be added:  
- An LldpConfiguration class with comment "Configuration of the LLDP protocol on the entire device." shall be added  
  - There shall be a composite association from the Lldp_Pac to the LldpConfiguration class with multiplicity [1] at both ends  
  - This association shall be represented by an Lldp_Pac::_lldpConfiguration : LldpConfiguration attribute  
- An LldpStatus class with comment "Status of the LLDP protocol on the local device." shall be added  
  - There shall be a composite association from the Lldp_Pac to the LldpStatus class with multiplicity [1] at both ends  
  - This association shall be represented by an Lldp_Pac::_lldpStatus : LldpStatus attribute  

The following attributes shall be added:  
- LocalSystemData::switchingProtocolOnOffIsAvail : boolean = false [1] with comment "If true, the device supports switching on/off the LLDP protocol for the entire device."  
- LldpConfiguration::protocolIsOn : boolean = false [1] with comment "If true, the LLDP protocol is enabled on the entire device."  
- LldpStatus::protocolIsUp : boolean = false [1] with comment "If true, the LLDP protocol is operational on the entire device."
