### ISSUE TITLE
LLDP protocol version selection

### ISSUE THREAD

**Issue by niloda** [openBackhaul/lldp#7]
Some devices support both V1 and V2 version of protocol.
Version 1 was defined in IEEE Std 802.1AB™-2005, while Version 2 was defined in IEEE Std 802.1AB™-2009.
With some limitations the two release are compatible (using the nearest bridge group MAC address 01-80-C2-00-00-0E in V2)

An attribute to select the running LLDP protocol version would be required.

**Comment by openBackhaul** [comment]
**Decision during the LF ONMI x-haul call on 11th of December 2024:**  

The following enumeration (shall translate into identityref in YANG) shall be added:  
- An LldpVersionType enumeration with comment "Versions of the LLDP protocol definition." shall be added  
- It shall comprise the following values:  
  - VERSION_1_IEEE_802_1AB_2005  
  - VERSION_2_IEEE_802_1AB_2009  
  - VERSION_NOT_YET_DEFINED  

The following attributes shall be added:  
- LocalSystemData::supportedVersionsOfLldpList : LldpVersionType [*] = [VERSION_NOT_YET_DEFINED] with comment "List of versions of LLDP that are supported by the device."  
- LldpConfiguration::activatedVersionOfLldp : LldpVersionType [1] = VERSION_NOT_YET_DEFINED with comment "Version of the LLDP protocol that is enabled on the device."  
- LldpStatus::operationalVersionOfLldp : LldpVersionType [1] = VERSION_NOT_YET_DEFINED with comment "Version of the LLDP protocol that is operational on the device."

**Comment by PrathibaJee** [comment]
>The following comment describes what UML2YANG tool expects from UML files to generate an identity ref and further how it will generate identityref. Adding this comment for our reference.

**Expectation from UML :**
In the UML, if a enumeration is defined with “isLeaf=false” advanced property , then UML2YANG tool will generate a typedef with identityref.

**What will be generated as a consequence :**
In our case, UML2YANG will generate , 

1. a base identity
```
identity VERSION {
    description
      "none";
  }
```
2. identities for each “owned literal” defined in the enumeration
```
identity VERSION_1_IEEE_802_1AB_2005 {
    base VERSION;
    description
      "none";
  }

  identity VERSION_2_IEEE_802_1AB_2009 {
    base VERSION;
    description
      "none";
  }

  identity VERSION_NOT_YET_DEFINED {
    base VERSION;
    description
      "none";
  }
```
3. typedef for the defined enumeration with an **identityref** that points to a base identity
```
typedef lldp-version-type {
    type identityref {
      base VERSION;
    }
    description
      "Versions of the LLDP protocol definition.";
  }
```

**Additional information :**
By including an identityref , we are enabling further submodules to define their own identity by inheriting the base identity.
For example in this case, In the submodules, new options shall be defined like this
```
identity VERSION_3_IEEE_802_1AB_2010 {
    base lldp:VERSION;
    description
      "none";
  }
```

**Comment by openBackhaul** [comment]
While documenting the [decision from 11th of December](https://github.com/openBackhaul/lldp/issues/7#issuecomment-2503424948) into the LLDP UML, the following findings have been made:  
- The multiplicity of the supportedVersionsOfLldpList attribute is stated to be [\*], but on the other hand a default value ([VERSION_NOT_YET_DEFINED]) has been defined. The multiplicity has been changed to [1..*] in the modelling.  
- The enumeration value "VERSION_NOT_YET_DEFINED" is a deviation from general custom. In general "NOT_YET_DEFINED" would be used. Enumeration value and default value have been changed to "NOT_YET_DEFINED"
