### ISSUE TITLE
LLDP protocol agents management

### ISSUE THREAD

**Issue by niloda** [openBackhaul/lldp#8]
Version 2 of the LLDP protocol allows to run multiple agent inside a device.

LLDP agents are classified into the following types (chapter **7. LLDPDU transmission, reception, and addressing** of **IEEE Std 802.1AB™-2016**):

- Nearest bridge agent (Group MAC addresses used by LLDP: 01-80-C2-00-00-0E). Propagation is constrained to a single
physical link; stopped by all types of bridge 
- Nearest non-TPMR bridge agent (Group MAC addresses used by LLDP: 01-80-C2-00-00-03). Propagation is constrained by all bridges other than TPMRs; intended for use within provider bridged networks.
- Nearest customer bridge agent (Group MAC addresses used by LLDP: 01-80-C2-00-00-00). Propagation is constrained by customer bridges; this gives the same coverage as a customer-customer MACSec connection.

A Two-port MAC Relay (TPMR) is a type of bridge that has only two externally-accessible bridge ports. It supports a subset of the features of a MAC bridge. 

To activate/deactivate an agent, an instance must be created/deleted in/from port-list.

To harmonize the instance creation/deletion to other YANG models, it is suggested to add specific RPCs.

**Comment by openBackhaul** [comment]
More details can be found here [LLDP agents and bridge modes](https://support.hpe.com/techhub/eginfolib/networking/docs/switches/5950/5200-4014a_l2-lan_cg/content/504054699.htm)

**Comment by openBackhaul** [comment]
**Decision during the LF ONMI x-haul call on 11th of December 2024:**  

The following interface shall be added:  
- An Interface with name LldpOperations shall be added. It shall be equipped with the comment "Group of operations for managing the LLDP agents on the device."  

The following Operations (RPCs) shall be added:   
- A createLldpPort operation shall be added to the LldpOperations interface.  
  - It shall be equipped with the following comment "Operation for creating an additional LLDP Agent. Default values of the device will be filled in during the CreateLldpPort operation. Operation is idempotent. If called with the values of the two input parameters identifying an already existing instance, no changes on the values of the existing instance shall be made and successful execution of the operation shall be indicated."
  - It shall have the following input parameters:
    - _name : LogicalTerminationPoint [1] with the following comment "UUID of the LogicalTerminationPoint (with LayerProtocol::layerProtocolName==LAYER_PROTOCOL_NAME_TYPE_ETHERNET_CONTAINER_LAYER) that shall serve the to be created LLDP agent (instance of PortType)."
    - destMacAddress:MacAddress [1] with the following comment "Type of LLDP protocol agent (destination MAC address) to be run on the to be created Port."
- A deleteLldpPort operation shall be added to the LldpOperations interface.  
  - It shall be equipped with the following comment "Operation for deleting an LLDP Agent. Operation is idempotent. If called with values of the two input parameters not identifying an existing instance, successful execution of the operation shall be indicated."
  - It shall have the following input parameters:
    - _name : LogicalTerminationPoint [1] with the following comment "UUID of the LogicalTerminationPoint (with LayerProtocol::layerProtocolName==LAYER_PROTOCOL_NAME_TYPE_ETHERNET_CONTAINER_LAYER) that serves the to be deleted LLDP agent (instance of PortType)."
    - destMacAddress:MacAddress [1] with the following comment "Type of LLDP protocol agent (destination MAC address) of the to be deleted Port."
